# ----------------------------------------------------------------------
# This code was automatically generated by the PythonTarget. Any changes made to this
# file will be overwritten during the next generation!
# ----------------------------------------------------------------------

from v1.Lexer.Location import Location
from v1.Parser.ParserInfos.Common.ClassModifier import ClassModifier
from v1.Parser.ParserInfos.Common.ConstraintParametersParserInfo import ConstraintParameterParserInfo
from v1.Parser.ParserInfos.Common.ConstraintParametersParserInfo import ConstraintParametersParserInfo
from v1.Parser.ParserInfos.Common.FuncArgumentsParserInfo import FuncArgumentParserInfo
from v1.Parser.ParserInfos.Common.FuncArgumentsParserInfo import FuncArgumentsParserInfo
from v1.Parser.ParserInfos.Common.FuncParametersParserInfo import FuncParameterParserInfo
from v1.Parser.ParserInfos.Common.FuncParametersParserInfo import FuncParametersParserInfo
from v1.Parser.ParserInfos.Common.MethodModifier import MethodModifier
from v1.Parser.ParserInfos.Common.MutabilityModifier import MutabilityModifier
from v1.Parser.ParserInfos.Common.TemplateParametersParserInfo import TemplateParametersParserInfo
from v1.Parser.ParserInfos.Common.TemplateParametersParserInfo import TemplateTypeParameterParserInfo
from v1.Parser.ParserInfos.Common.VisibilityModifier import VisibilityModifier
from v1.Parser.ParserInfos.Expressions.BinaryExpressionParserInfo import BinaryExpressionParserInfo, OperatorType as BinaryExpressionOperatorType
from v1.Parser.ParserInfos.Expressions.CallExpressionParserInfo import CallExpressionParserInfo
from v1.Parser.ParserInfos.Expressions.FuncOrTypeExpressionParserInfo import FuncOrTypeExpressionParserInfo
from v1.Parser.ParserInfos.Expressions.NoneExpressionParserInfo import NoneExpressionParserInfo
from v1.Parser.ParserInfos.Expressions.TypeCheckExpressionParserInfo import TypeCheckExpressionParserInfo, OperatorType as TypeCheckExpressionParserInfoOperatorType
from v1.Parser.ParserInfos.Expressions.VariableExpressionParserInfo import VariableExpressionParserInfo
from v1.Parser.ParserInfos.ParserInfo import ParserInfoType
from v1.Parser.ParserInfos.Statements.ClassCapabilities.ConceptCapabilities import ConceptCapabilities
from v1.Parser.ParserInfos.Statements.ClassCapabilities.ExceptionCapabilities import ExceptionCapabilities
from v1.Parser.ParserInfos.Statements.ClassCapabilities.ImmutablePODCapabilities import ImmutablePODCapabilities
from v1.Parser.ParserInfos.Statements.ClassCapabilities.InterfaceCapabilities import InterfaceCapabilities
from v1.Parser.ParserInfos.Statements.ClassCapabilities.MixinCapabilities import MixinCapabilities
from v1.Parser.ParserInfos.Statements.ClassCapabilities.MutablePODCapabilities import MutablePODCapabilities
from v1.Parser.ParserInfos.Statements.ClassCapabilities.StandardCapabilities import StandardCapabilities
from v1.Parser.ParserInfos.Statements.ClassStatementParserInfo import ClassStatementParserInfo
from v1.Parser.ParserInfos.Statements.FuncDefinitionStatementParserInfo import FuncDefinitionStatementParserInfo, OperatorType as FuncDefinitionStatementParserInfoOperatorType
from v1.Parser.ParserInfos.Statements.SpecialMethodStatementParserInfo import SpecialMethodStatementParserInfo, SpecialMethodType
from v1.Parser.ParserInfos.Types.StandardTypeParserInfo import StandardTypeParserInfo, StandardTypeItemParserInfo
from v1.Parser.ParserInfos.Types.VariantTypeParserInfo import VariantTypeParserInfo
from v1.Parser.Region import Region


# ----------------------------------------------------------------------
statement00200006_00200009 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=20, column=6), end=Location(line=20, column=9)), Region(begin=Location(line=20, column=6), end=Location(line=20, column=9))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00200006_00200009 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=20, column=6), end=Location(line=20, column=9)), None, Region(begin=Location(line=20, column=6), end=Location(line=20, column=9))],
    mutability_modifier=None,
    items=[statement00200006_00200009, ],
)

statement00200012_00200016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=20, column=12), end=Location(line=20, column=16)), Region(begin=Location(line=20, column=12), end=Location(line=20, column=16))],
    name="None",
    templates=None,
    constraints=None,
)

statement00200012_00200016 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=20, column=12), end=Location(line=20, column=16)), None, Region(begin=Location(line=20, column=12), end=Location(line=20, column=16))],
    mutability_modifier=None,
    items=[statement00200012_00200016, ],
)

statement00200005_00200017 = VariantTypeParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=20, column=5), end=Location(line=20, column=17)), None, Region(begin=Location(line=20, column=5), end=Location(line=20, column=17))],
    mutability_modifier=None,
    types=[statement00200006_00200009, statement00200012_00200016, ],
)

statement00200031_00200035 = NoneExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=20, column=31), end=Location(line=20, column=35))],
)

statement00200005_00200035 = ConstraintParameterParserInfo.Create(
    regions=[Region(begin=Location(line=20, column=5), end=Location(line=20, column=35)), Region(begin=Location(line=20, column=18), end=Location(line=20, column=28))],
    type=statement00200005_00200017,
    name="min_value!",
    default_value=statement00200031_00200035,
)

statement00210006_00210009 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=21, column=6), end=Location(line=21, column=9)), Region(begin=Location(line=21, column=6), end=Location(line=21, column=9))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00210006_00210009 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=21, column=6), end=Location(line=21, column=9)), None, Region(begin=Location(line=21, column=6), end=Location(line=21, column=9))],
    mutability_modifier=None,
    items=[statement00210006_00210009, ],
)

statement00210012_00210016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=21, column=12), end=Location(line=21, column=16)), Region(begin=Location(line=21, column=12), end=Location(line=21, column=16))],
    name="None",
    templates=None,
    constraints=None,
)

statement00210012_00210016 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=21, column=12), end=Location(line=21, column=16)), None, Region(begin=Location(line=21, column=12), end=Location(line=21, column=16))],
    mutability_modifier=None,
    items=[statement00210012_00210016, ],
)

statement00210005_00210017 = VariantTypeParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=21, column=5), end=Location(line=21, column=17)), None, Region(begin=Location(line=21, column=5), end=Location(line=21, column=17))],
    mutability_modifier=None,
    types=[statement00210006_00210009, statement00210012_00210016, ],
)

statement00210031_00210035 = NoneExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=21, column=31), end=Location(line=21, column=35))],
)

statement00210005_00210035 = ConstraintParameterParserInfo.Create(
    regions=[Region(begin=Location(line=21, column=5), end=Location(line=21, column=35)), Region(begin=Location(line=21, column=18), end=Location(line=21, column=28))],
    type=statement00210005_00210017,
    name="max_value!",
    default_value=statement00210031_00210035,
)

statement00190030_00220002 = ConstraintParametersParserInfo.Create(
    regions=[Region(begin=Location(line=19, column=30), end=Location(line=22, column=2)), None, Region(begin=Location(line=20, column=5), end=Location(line=21, column=36)), None],
    positional=None,
    any=[statement00200005_00200035, statement00210005_00210035, ],
    keyword=None,
)

statement00240009_00240016 = FuncOrTypeExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=9), end=Location(line=24, column=16)), None, Region(begin=Location(line=24, column=9), end=Location(line=24, column=16))],
    is_compile_time=False,
    name="Enforce",
)

statement00240017_00240027 = VariableExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=17), end=Location(line=24, column=27)), Region(begin=Location(line=24, column=26), end=Location(line=24, column=27)), Region(begin=Location(line=24, column=17), end=Location(line=24, column=27))],
    is_compile_time=True,
    name="min_value!",
)

statement00240031_00240035 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=31), end=Location(line=24, column=35)), Region(begin=Location(line=24, column=31), end=Location(line=24, column=35))],
    name="None",
    templates=None,
    constraints=None,
)

statement00240031_00240035 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=31), end=Location(line=24, column=35)), None, Region(begin=Location(line=24, column=31), end=Location(line=24, column=35))],
    mutability_modifier=None,
    items=[statement00240031_00240035, ],
)

statement00240017_00240035 = TypeCheckExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=17), end=Location(line=24, column=35)), Region(begin=Location(line=24, column=28), end=Location(line=24, column=30))],
    operator=TypeCheckExpressionParserInfoOperatorType.Is,
    expression=statement00240017_00240027,
    type=statement00240031_00240035,
)

statement00240039_00240049 = VariableExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=39), end=Location(line=24, column=49)), Region(begin=Location(line=24, column=48), end=Location(line=24, column=49)), Region(begin=Location(line=24, column=39), end=Location(line=24, column=49))],
    is_compile_time=True,
    name="max_value!",
)

statement00240053_00240057 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=53), end=Location(line=24, column=57)), Region(begin=Location(line=24, column=53), end=Location(line=24, column=57))],
    name="None",
    templates=None,
    constraints=None,
)

statement00240053_00240057 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=53), end=Location(line=24, column=57)), None, Region(begin=Location(line=24, column=53), end=Location(line=24, column=57))],
    mutability_modifier=None,
    items=[statement00240053_00240057, ],
)

statement00240039_00240057 = TypeCheckExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=39), end=Location(line=24, column=57)), Region(begin=Location(line=24, column=50), end=Location(line=24, column=52))],
    operator=TypeCheckExpressionParserInfoOperatorType.Is,
    expression=statement00240039_00240049,
    type=statement00240053_00240057,
)

statement00240061_00240071 = VariableExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=61), end=Location(line=24, column=71)), Region(begin=Location(line=24, column=70), end=Location(line=24, column=71)), Region(begin=Location(line=24, column=61), end=Location(line=24, column=71))],
    is_compile_time=True,
    name="min_value!",
)

statement00240075_00240085 = VariableExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=75), end=Location(line=24, column=85)), Region(begin=Location(line=24, column=84), end=Location(line=24, column=85)), Region(begin=Location(line=24, column=75), end=Location(line=24, column=85))],
    is_compile_time=True,
    name="max_value!",
)

statement00240061_00240085 = BinaryExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=61), end=Location(line=24, column=85)), Region(begin=Location(line=24, column=72), end=Location(line=24, column=74))],
    left_expression=statement00240061_00240071,
    operator=BinaryExpressionOperatorType.LessEqual,
    right_expression=statement00240075_00240085,
)

statement00240039_00240085 = BinaryExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=39), end=Location(line=24, column=85)), Region(begin=Location(line=24, column=58), end=Location(line=24, column=60))],
    left_expression=statement00240039_00240057,
    operator=BinaryExpressionOperatorType.LogicalOr,
    right_expression=statement00240061_00240085,
)

statement00240017_00240085 = BinaryExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=17), end=Location(line=24, column=85)), Region(begin=Location(line=24, column=36), end=Location(line=24, column=38))],
    left_expression=statement00240017_00240035,
    operator=BinaryExpressionOperatorType.LogicalOr,
    right_expression=statement00240039_00240085,
)

statement00240017_00240085 = FuncArgumentParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=24, column=17), end=Location(line=24, column=85)), None],
    expression=statement00240017_00240085,
    keyword=None,
)

statement00240016_00240086 = FuncArgumentsParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=16), end=Location(line=24, column=86)), Region(begin=Location(line=24, column=16), end=Location(line=24, column=86))],
    arguments=[statement00240017_00240085, ],
)

statement00240009_00240086 = CallExpressionParserInfo.Create(
    regions=[Region(begin=Location(line=24, column=9), end=Location(line=24, column=86)), Region(begin=Location(line=24, column=16), end=Location(line=24, column=86))],
    expression=statement00240009_00240016,
    arguments=statement00240016_00240086,
)

statement00230005_00260005 = SpecialMethodStatementParserInfo.Create(
    regions=[Region(begin=Location(line=23, column=5), end=Location(line=26, column=5)), Region(begin=Location(line=23, column=5), end=Location(line=23, column=25)), Region(begin=Location(line=23, column=27), end=Location(line=26, column=5))],
    class_capabilities=ConceptCapabilities,
    the_type=SpecialMethodType.CompileTimeEvalConstraints,
    statements=[statement00240009_00240086, ],
)

statement00260021_00260029 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=26, column=21), end=Location(line=26, column=29)), Region(begin=Location(line=26, column=21), end=Location(line=26, column=29))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00260021_00260033 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=26, column=21), end=Location(line=26, column=33)), Region(begin=Location(line=26, column=30), end=Location(line=26, column=33)), Region(begin=Location(line=26, column=21), end=Location(line=26, column=29))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00260021_00260029, ],
)

statement00260051_00260059 = TemplateTypeParameterParserInfo.Create(
    regions=[Region(begin=Location(line=26, column=51), end=Location(line=26, column=59)), Region(begin=Location(line=26, column=51), end=Location(line=26, column=59)), None],
    name="ArchiveT",
    is_variadic=None,
    default_type=None,
)

statement00260050_00260060 = TemplateParametersParserInfo.Create(
    regions=[Region(begin=Location(line=26, column=50), end=Location(line=26, column=60)), None, Region(begin=Location(line=26, column=51), end=Location(line=26, column=59)), None],
    positional=None,
    any=[statement00260051_00260059, ],
    keyword=None,
)

statement00260061_00260069 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=26, column=61), end=Location(line=26, column=69)), Region(begin=Location(line=26, column=61), end=Location(line=26, column=69))],
    name="ArchiveT",
    templates=None,
    constraints=None,
)

statement00260061_00260073 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=26, column=61), end=Location(line=26, column=73)), Region(begin=Location(line=26, column=70), end=Location(line=26, column=73)), Region(begin=Location(line=26, column=61), end=Location(line=26, column=69))],
    mutability_modifier=MutabilityModifier.ref,
    items=[statement00260061_00260069, ],
)

statement00260061_00260081 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=26, column=61), end=Location(line=26, column=81)), None, None, Region(begin=Location(line=26, column=74), end=Location(line=26, column=81))],  # type: ignore
    is_compile_time=False,
    type=statement00260061_00260073,
    is_variadic=None,
    name="archive",
    default_value=None,
)

statement00260060_00260082 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=26, column=60), end=Location(line=26, column=82)), None, Region(begin=Location(line=26, column=61), end=Location(line=26, column=81)), None],
    positional=None,
    any_args=[statement00260061_00260081, ],
    keyword=None,
)

statement00260005_00270001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=26, column=5), end=Location(line=27, column=1)), Region(begin=Location(line=26, column=14), end=Location(line=26, column=20)), None, Region(begin=Location(line=26, column=5), end=Location(line=27, column=1)), Region(begin=Location(line=26, column=34), end=Location(line=26, column=50)), None, None, Region(begin=Location(line=26, column=60), end=Location(line=26, column=82)), None, None, None, None, None, None, Region(begin=Location(line=26, column=6), end=Location(line=26, column=12))],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=None,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00260021_00260033,
    name=FuncDefinitionStatementParserInfoOperatorType.Deserialize,
    documentation=None,
    templates=statement00260050_00260060,
    captured_variables=None,
    parameters=statement00260060_00260082,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=True,
)

statement00270032_00270040 = TemplateTypeParameterParserInfo.Create(
    regions=[Region(begin=Location(line=27, column=32), end=Location(line=27, column=40)), Region(begin=Location(line=27, column=32), end=Location(line=27, column=40)), None],
    name="ArchiveT",
    is_variadic=None,
    default_type=None,
)

statement00270031_00270041 = TemplateParametersParserInfo.Create(
    regions=[Region(begin=Location(line=27, column=31), end=Location(line=27, column=41)), None, Region(begin=Location(line=27, column=32), end=Location(line=27, column=40)), None],
    positional=None,
    any=[statement00270032_00270040, ],
    keyword=None,
)

statement00270042_00270050 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=27, column=42), end=Location(line=27, column=50)), Region(begin=Location(line=27, column=42), end=Location(line=27, column=50))],
    name="ArchiveT",
    templates=None,
    constraints=None,
)

statement00270042_00270054 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=27, column=42), end=Location(line=27, column=54)), Region(begin=Location(line=27, column=51), end=Location(line=27, column=54)), Region(begin=Location(line=27, column=42), end=Location(line=27, column=50))],
    mutability_modifier=MutabilityModifier.ref,
    items=[statement00270042_00270050, ],
)

statement00270042_00270062 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=27, column=42), end=Location(line=27, column=62)), None, None, Region(begin=Location(line=27, column=55), end=Location(line=27, column=62))],  # type: ignore
    is_compile_time=False,
    type=statement00270042_00270054,
    is_variadic=None,
    name="archive",
    default_value=None,
)

statement00270041_00270063 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=27, column=41), end=Location(line=27, column=63)), None, Region(begin=Location(line=27, column=42), end=Location(line=27, column=62)), None],
    positional=None,
    any_args=[statement00270042_00270062, ],
    keyword=None,
)

statement00270005_00290001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=27, column=5), end=Location(line=29, column=1)), Region(begin=Location(line=27, column=5), end=Location(line=27, column=11)), Region(begin=Location(line=27, column=64), end=Location(line=27, column=73)), Region(begin=Location(line=27, column=5), end=Location(line=29, column=1)), Region(begin=Location(line=27, column=17), end=Location(line=27, column=31)), None, None, Region(begin=Location(line=27, column=41), end=Location(line=27, column=63)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=None,
    name=FuncDefinitionStatementParserInfoOperatorType.Serialize,
    documentation=None,
    templates=statement00270031_00270041,
    captured_variables=None,
    parameters=statement00270041_00270063,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00290029_00290037 = TemplateTypeParameterParserInfo.Create(
    regions=[Region(begin=Location(line=29, column=29), end=Location(line=29, column=37)), Region(begin=Location(line=29, column=29), end=Location(line=29, column=37)), None],
    name="VisitorT",
    is_variadic=None,
    default_type=None,
)

statement00290028_00290038 = TemplateParametersParserInfo.Create(
    regions=[Region(begin=Location(line=29, column=28), end=Location(line=29, column=38)), None, Region(begin=Location(line=29, column=29), end=Location(line=29, column=37)), None],
    positional=None,
    any=[statement00290029_00290037, ],
    keyword=None,
)

statement00290039_00290047 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=29, column=39), end=Location(line=29, column=47)), Region(begin=Location(line=29, column=39), end=Location(line=29, column=47))],
    name="VisitorT",
    templates=None,
    constraints=None,
)

statement00290039_00290051 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=29, column=39), end=Location(line=29, column=51)), Region(begin=Location(line=29, column=48), end=Location(line=29, column=51)), Region(begin=Location(line=29, column=39), end=Location(line=29, column=47))],
    mutability_modifier=MutabilityModifier.ref,
    items=[statement00290039_00290047, ],
)

statement00290039_00290059 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=29, column=39), end=Location(line=29, column=59)), None, None, Region(begin=Location(line=29, column=52), end=Location(line=29, column=59))],  # type: ignore
    is_compile_time=False,
    type=statement00290039_00290051,
    is_variadic=None,
    name="visitor",
    default_value=None,
)

statement00290038_00290060 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=29, column=38), end=Location(line=29, column=60)), None, Region(begin=Location(line=29, column=39), end=Location(line=29, column=59)), None],
    positional=None,
    any_args=[statement00290039_00290059, ],
    keyword=None,
)

statement00290005_00310001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=29, column=5), end=Location(line=31, column=1)), Region(begin=Location(line=29, column=5), end=Location(line=29, column=11)), Region(begin=Location(line=29, column=61), end=Location(line=29, column=70)), Region(begin=Location(line=29, column=5), end=Location(line=31, column=1)), Region(begin=Location(line=29, column=17), end=Location(line=29, column=28)), None, None, Region(begin=Location(line=29, column=38), end=Location(line=29, column=60)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=None,
    name=FuncDefinitionStatementParserInfoOperatorType.Accept,
    documentation=None,
    templates=statement00290028_00290038,
    captured_variables=None,
    parameters=statement00290038_00290060,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00310012_00310020 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=31, column=12), end=Location(line=31, column=20)), Region(begin=Location(line=31, column=12), end=Location(line=31, column=20))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00310012_00310024 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=31, column=12), end=Location(line=31, column=24)), Region(begin=Location(line=31, column=21), end=Location(line=31, column=24)), Region(begin=Location(line=31, column=12), end=Location(line=31, column=20))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00310012_00310020, ],
)

statement00310005_00330001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=31, column=5), end=Location(line=33, column=1)), Region(begin=Location(line=31, column=5), end=Location(line=31, column=11)), Region(begin=Location(line=31, column=38), end=Location(line=31, column=47)), Region(begin=Location(line=31, column=5), end=Location(line=33, column=1)), Region(begin=Location(line=31, column=25), end=Location(line=31, column=35)), None, None, Region(begin=Location(line=31, column=35), end=Location(line=31, column=37)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00310012_00310024,
    name=FuncDefinitionStatementParserInfoOperatorType.Clone,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=True,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00330012_00330016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=33, column=12), end=Location(line=33, column=16)), Region(begin=Location(line=33, column=12), end=Location(line=33, column=16))],
    name="Bool",
    templates=None,
    constraints=None,
)

statement00330012_00330020 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=33, column=12), end=Location(line=33, column=20)), Region(begin=Location(line=33, column=17), end=Location(line=33, column=20)), Region(begin=Location(line=33, column=12), end=Location(line=33, column=16))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00330012_00330016, ],
)

statement00330005_00340001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=33, column=5), end=Location(line=34, column=1)), Region(begin=Location(line=33, column=5), end=Location(line=33, column=11)), Region(begin=Location(line=33, column=34), end=Location(line=33, column=43)), Region(begin=Location(line=33, column=5), end=Location(line=34, column=1)), Region(begin=Location(line=33, column=21), end=Location(line=33, column=31)), None, None, Region(begin=Location(line=33, column=31), end=Location(line=33, column=33)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00330012_00330020,
    name=FuncDefinitionStatementParserInfoOperatorType.ToBool,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=True,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00340012_00340015 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=34, column=12), end=Location(line=34, column=15)), Region(begin=Location(line=34, column=12), end=Location(line=34, column=15))],
    name="Str",
    templates=None,
    constraints=None,
)

statement00340012_00340019 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=34, column=12), end=Location(line=34, column=19)), Region(begin=Location(line=34, column=16), end=Location(line=34, column=19)), Region(begin=Location(line=34, column=12), end=Location(line=34, column=15))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00340012_00340015, ],
)

statement00340005_00360001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=34, column=5), end=Location(line=36, column=1)), Region(begin=Location(line=34, column=5), end=Location(line=34, column=11)), Region(begin=Location(line=34, column=36), end=Location(line=34, column=45)), Region(begin=Location(line=34, column=5), end=Location(line=36, column=1)), Region(begin=Location(line=34, column=20), end=Location(line=34, column=33)), None, None, Region(begin=Location(line=34, column=33), end=Location(line=34, column=35)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00340012_00340019,
    name=FuncDefinitionStatementParserInfoOperatorType.ToString,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=True,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00360021_00360034 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=21), end=Location(line=36, column=34)), Region(begin=Location(line=36, column=21), end=Location(line=36, column=34))],
    name="CompareResult",
    templates=None,
    constraints=None,
)

statement00360021_00360038 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=21), end=Location(line=36, column=38)), Region(begin=Location(line=36, column=35), end=Location(line=36, column=38)), Region(begin=Location(line=36, column=21), end=Location(line=36, column=34))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00360021_00360034, ],
)

statement00360051_00360059 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=51), end=Location(line=36, column=59)), Region(begin=Location(line=36, column=51), end=Location(line=36, column=59))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00360051_00360069 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=51), end=Location(line=36, column=69)), Region(begin=Location(line=36, column=60), end=Location(line=36, column=69)), Region(begin=Location(line=36, column=51), end=Location(line=36, column=59))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00360051_00360059, ],
)

statement00360051_00360074 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=51), end=Location(line=36, column=74)), None, None, Region(begin=Location(line=36, column=70), end=Location(line=36, column=74))],  # type: ignore
    is_compile_time=False,
    type=statement00360051_00360069,
    is_variadic=None,
    name="this",
    default_value=None,
)

statement00360076_00360082 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=76), end=Location(line=36, column=82)), Region(begin=Location(line=36, column=76), end=Location(line=36, column=82))],
    name="Number",
    templates=None,
    constraints=None,
)

statement00360076_00360092 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=76), end=Location(line=36, column=92)), Region(begin=Location(line=36, column=83), end=Location(line=36, column=92)), Region(begin=Location(line=36, column=76), end=Location(line=36, column=82))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00360076_00360082, ],
)

statement00360076_00360097 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=76), end=Location(line=36, column=97)), None, None, Region(begin=Location(line=36, column=93), end=Location(line=36, column=97))],  # type: ignore
    is_compile_time=False,
    type=statement00360076_00360092,
    is_variadic=None,
    name="that",
    default_value=None,
)

statement00360050_00360098 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=36, column=50), end=Location(line=36, column=98)), None, Region(begin=Location(line=36, column=51), end=Location(line=36, column=97)), None],
    positional=None,
    any_args=[statement00360051_00360074, statement00360076_00360097, ],
    keyword=None,
)

statement00360005_00380001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=36, column=5), end=Location(line=38, column=1)), Region(begin=Location(line=36, column=14), end=Location(line=36, column=20)), None, Region(begin=Location(line=36, column=5), end=Location(line=38, column=1)), Region(begin=Location(line=36, column=39), end=Location(line=36, column=50)), None, None, Region(begin=Location(line=36, column=50), end=Location(line=36, column=98)), None, None, None, None, None, None, Region(begin=Location(line=36, column=6), end=Location(line=36, column=12))],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=None,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00360021_00360038,
    name=FuncDefinitionStatementParserInfoOperatorType.Compare,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00360050_00360098,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=True,
)

statement00380012_00380016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=38, column=12), end=Location(line=38, column=16)), Region(begin=Location(line=38, column=12), end=Location(line=38, column=16))],
    name="Bool",
    templates=None,
    constraints=None,
)

statement00380012_00380020 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=38, column=12), end=Location(line=38, column=20)), Region(begin=Location(line=38, column=17), end=Location(line=38, column=20)), Region(begin=Location(line=38, column=12), end=Location(line=38, column=16))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00380012_00380016, ],
)

statement00380031_00380034 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=38, column=31), end=Location(line=38, column=34)), Region(begin=Location(line=38, column=31), end=Location(line=38, column=34))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00380031_00380044 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=38, column=31), end=Location(line=38, column=44)), Region(begin=Location(line=38, column=35), end=Location(line=38, column=44)), Region(begin=Location(line=38, column=31), end=Location(line=38, column=34))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00380031_00380034, ],
)

statement00380031_00380049 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=38, column=31), end=Location(line=38, column=49)), None, None, Region(begin=Location(line=38, column=45), end=Location(line=38, column=49))],  # type: ignore
    is_compile_time=False,
    type=statement00380031_00380044,
    is_variadic=None,
    name="that",
    default_value=None,
)

statement00380030_00380050 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=38, column=30), end=Location(line=38, column=50)), None, Region(begin=Location(line=38, column=31), end=Location(line=38, column=49)), None],
    positional=None,
    any_args=[statement00380031_00380049, ],
    keyword=None,
)

statement00380005_00390001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=38, column=5), end=Location(line=39, column=1)), Region(begin=Location(line=38, column=5), end=Location(line=38, column=11)), Region(begin=Location(line=38, column=51), end=Location(line=38, column=60)), Region(begin=Location(line=38, column=5), end=Location(line=39, column=1)), Region(begin=Location(line=38, column=21), end=Location(line=38, column=30)), None, None, Region(begin=Location(line=38, column=30), end=Location(line=38, column=50)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00380012_00380020,
    name=FuncDefinitionStatementParserInfoOperatorType.Equal,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00380030_00380050,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00390012_00390016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=39, column=12), end=Location(line=39, column=16)), Region(begin=Location(line=39, column=12), end=Location(line=39, column=16))],
    name="Bool",
    templates=None,
    constraints=None,
)

statement00390012_00390020 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=39, column=12), end=Location(line=39, column=20)), Region(begin=Location(line=39, column=17), end=Location(line=39, column=20)), Region(begin=Location(line=39, column=12), end=Location(line=39, column=16))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00390012_00390016, ],
)

statement00390034_00390037 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=39, column=34), end=Location(line=39, column=37)), Region(begin=Location(line=39, column=34), end=Location(line=39, column=37))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00390034_00390047 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=39, column=34), end=Location(line=39, column=47)), Region(begin=Location(line=39, column=38), end=Location(line=39, column=47)), Region(begin=Location(line=39, column=34), end=Location(line=39, column=37))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00390034_00390037, ],
)

statement00390034_00390052 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=39, column=34), end=Location(line=39, column=52)), None, None, Region(begin=Location(line=39, column=48), end=Location(line=39, column=52))],  # type: ignore
    is_compile_time=False,
    type=statement00390034_00390047,
    is_variadic=None,
    name="that",
    default_value=None,
)

statement00390033_00390053 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=39, column=33), end=Location(line=39, column=53)), None, Region(begin=Location(line=39, column=34), end=Location(line=39, column=52)), None],
    positional=None,
    any_args=[statement00390034_00390052, ],
    keyword=None,
)

statement00390005_00400001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=39, column=5), end=Location(line=40, column=1)), Region(begin=Location(line=39, column=5), end=Location(line=39, column=11)), Region(begin=Location(line=39, column=54), end=Location(line=39, column=63)), Region(begin=Location(line=39, column=5), end=Location(line=40, column=1)), Region(begin=Location(line=39, column=21), end=Location(line=39, column=33)), None, None, Region(begin=Location(line=39, column=33), end=Location(line=39, column=53)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00390012_00390020,
    name=FuncDefinitionStatementParserInfoOperatorType.NotEqual,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00390033_00390053,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00400012_00400016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=40, column=12), end=Location(line=40, column=16)), Region(begin=Location(line=40, column=12), end=Location(line=40, column=16))],
    name="Bool",
    templates=None,
    constraints=None,
)

statement00400012_00400020 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=40, column=12), end=Location(line=40, column=20)), Region(begin=Location(line=40, column=17), end=Location(line=40, column=20)), Region(begin=Location(line=40, column=12), end=Location(line=40, column=16))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00400012_00400016, ],
)

statement00400030_00400033 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=40, column=30), end=Location(line=40, column=33)), Region(begin=Location(line=40, column=30), end=Location(line=40, column=33))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00400030_00400043 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=40, column=30), end=Location(line=40, column=43)), Region(begin=Location(line=40, column=34), end=Location(line=40, column=43)), Region(begin=Location(line=40, column=30), end=Location(line=40, column=33))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00400030_00400033, ],
)

statement00400030_00400048 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=40, column=30), end=Location(line=40, column=48)), None, None, Region(begin=Location(line=40, column=44), end=Location(line=40, column=48))],  # type: ignore
    is_compile_time=False,
    type=statement00400030_00400043,
    is_variadic=None,
    name="that",
    default_value=None,
)

statement00400029_00400049 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=40, column=29), end=Location(line=40, column=49)), None, Region(begin=Location(line=40, column=30), end=Location(line=40, column=48)), None],
    positional=None,
    any_args=[statement00400030_00400048, ],
    keyword=None,
)

statement00400005_00410001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=40, column=5), end=Location(line=41, column=1)), Region(begin=Location(line=40, column=5), end=Location(line=40, column=11)), Region(begin=Location(line=40, column=50), end=Location(line=40, column=59)), Region(begin=Location(line=40, column=5), end=Location(line=41, column=1)), Region(begin=Location(line=40, column=21), end=Location(line=40, column=29)), None, None, Region(begin=Location(line=40, column=29), end=Location(line=40, column=49)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00400012_00400020,
    name=FuncDefinitionStatementParserInfoOperatorType.Less,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00400029_00400049,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00410012_00410016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=41, column=12), end=Location(line=41, column=16)), Region(begin=Location(line=41, column=12), end=Location(line=41, column=16))],
    name="Bool",
    templates=None,
    constraints=None,
)

statement00410012_00410020 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=41, column=12), end=Location(line=41, column=20)), Region(begin=Location(line=41, column=17), end=Location(line=41, column=20)), Region(begin=Location(line=41, column=12), end=Location(line=41, column=16))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00410012_00410016, ],
)

statement00410035_00410038 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=41, column=35), end=Location(line=41, column=38)), Region(begin=Location(line=41, column=35), end=Location(line=41, column=38))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00410035_00410048 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=41, column=35), end=Location(line=41, column=48)), Region(begin=Location(line=41, column=39), end=Location(line=41, column=48)), Region(begin=Location(line=41, column=35), end=Location(line=41, column=38))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00410035_00410038, ],
)

statement00410035_00410053 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=41, column=35), end=Location(line=41, column=53)), None, None, Region(begin=Location(line=41, column=49), end=Location(line=41, column=53))],  # type: ignore
    is_compile_time=False,
    type=statement00410035_00410048,
    is_variadic=None,
    name="that",
    default_value=None,
)

statement00410034_00410054 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=41, column=34), end=Location(line=41, column=54)), None, Region(begin=Location(line=41, column=35), end=Location(line=41, column=53)), None],
    positional=None,
    any_args=[statement00410035_00410053, ],
    keyword=None,
)

statement00410005_00420001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=41, column=5), end=Location(line=42, column=1)), Region(begin=Location(line=41, column=5), end=Location(line=41, column=11)), Region(begin=Location(line=41, column=55), end=Location(line=41, column=64)), Region(begin=Location(line=41, column=5), end=Location(line=42, column=1)), Region(begin=Location(line=41, column=21), end=Location(line=41, column=34)), None, None, Region(begin=Location(line=41, column=34), end=Location(line=41, column=54)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00410012_00410020,
    name=FuncDefinitionStatementParserInfoOperatorType.LessEqual,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00410034_00410054,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00420012_00420016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=42, column=12), end=Location(line=42, column=16)), Region(begin=Location(line=42, column=12), end=Location(line=42, column=16))],
    name="Bool",
    templates=None,
    constraints=None,
)

statement00420012_00420020 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=42, column=12), end=Location(line=42, column=20)), Region(begin=Location(line=42, column=17), end=Location(line=42, column=20)), Region(begin=Location(line=42, column=12), end=Location(line=42, column=16))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00420012_00420016, ],
)

statement00420033_00420036 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=42, column=33), end=Location(line=42, column=36)), Region(begin=Location(line=42, column=33), end=Location(line=42, column=36))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00420033_00420046 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=42, column=33), end=Location(line=42, column=46)), Region(begin=Location(line=42, column=37), end=Location(line=42, column=46)), Region(begin=Location(line=42, column=33), end=Location(line=42, column=36))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00420033_00420036, ],
)

statement00420033_00420051 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=42, column=33), end=Location(line=42, column=51)), None, None, Region(begin=Location(line=42, column=47), end=Location(line=42, column=51))],  # type: ignore
    is_compile_time=False,
    type=statement00420033_00420046,
    is_variadic=None,
    name="that",
    default_value=None,
)

statement00420032_00420052 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=42, column=32), end=Location(line=42, column=52)), None, Region(begin=Location(line=42, column=33), end=Location(line=42, column=51)), None],
    positional=None,
    any_args=[statement00420033_00420051, ],
    keyword=None,
)

statement00420005_00430001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=42, column=5), end=Location(line=43, column=1)), Region(begin=Location(line=42, column=5), end=Location(line=42, column=11)), Region(begin=Location(line=42, column=53), end=Location(line=42, column=62)), Region(begin=Location(line=42, column=5), end=Location(line=43, column=1)), Region(begin=Location(line=42, column=21), end=Location(line=42, column=32)), None, None, Region(begin=Location(line=42, column=32), end=Location(line=42, column=52)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00420012_00420020,
    name=FuncDefinitionStatementParserInfoOperatorType.Greater,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00420032_00420052,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00430012_00430016 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=43, column=12), end=Location(line=43, column=16)), Region(begin=Location(line=43, column=12), end=Location(line=43, column=16))],
    name="Bool",
    templates=None,
    constraints=None,
)

statement00430012_00430020 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=43, column=12), end=Location(line=43, column=20)), Region(begin=Location(line=43, column=17), end=Location(line=43, column=20)), Region(begin=Location(line=43, column=12), end=Location(line=43, column=16))],
    mutability_modifier=MutabilityModifier.val,
    items=[statement00430012_00430016, ],
)

statement00430038_00430041 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=43, column=38), end=Location(line=43, column=41)), Region(begin=Location(line=43, column=38), end=Location(line=43, column=41))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00430038_00430051 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=43, column=38), end=Location(line=43, column=51)), Region(begin=Location(line=43, column=42), end=Location(line=43, column=51)), Region(begin=Location(line=43, column=38), end=Location(line=43, column=41))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00430038_00430041, ],
)

statement00430038_00430056 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=43, column=38), end=Location(line=43, column=56)), None, None, Region(begin=Location(line=43, column=52), end=Location(line=43, column=56))],  # type: ignore
    is_compile_time=False,
    type=statement00430038_00430051,
    is_variadic=None,
    name="that",
    default_value=None,
)

statement00430037_00430057 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=43, column=37), end=Location(line=43, column=57)), None, Region(begin=Location(line=43, column=38), end=Location(line=43, column=56)), None],
    positional=None,
    any_args=[statement00430038_00430056, ],
    keyword=None,
)

statement00430005_00450001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=43, column=5), end=Location(line=45, column=1)), Region(begin=Location(line=43, column=5), end=Location(line=43, column=11)), Region(begin=Location(line=43, column=58), end=Location(line=43, column=67)), Region(begin=Location(line=43, column=5), end=Location(line=45, column=1)), Region(begin=Location(line=43, column=21), end=Location(line=43, column=37)), None, None, Region(begin=Location(line=43, column=37), end=Location(line=43, column=57)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00430012_00430020,
    name=FuncDefinitionStatementParserInfoOperatorType.GreaterEqual,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00430037_00430057,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00450012_00450020 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=45, column=12), end=Location(line=45, column=20)), Region(begin=Location(line=45, column=12), end=Location(line=45, column=20))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00450012_00450024 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=45, column=12), end=Location(line=45, column=24)), Region(begin=Location(line=45, column=21), end=Location(line=45, column=24)), Region(begin=Location(line=45, column=12), end=Location(line=45, column=20))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00450012_00450020, ],
)

statement00450005_00460001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=45, column=5), end=Location(line=46, column=1)), Region(begin=Location(line=45, column=5), end=Location(line=45, column=11)), Region(begin=Location(line=45, column=41), end=Location(line=45, column=50)), Region(begin=Location(line=45, column=5), end=Location(line=46, column=1)), Region(begin=Location(line=45, column=25), end=Location(line=45, column=38)), None, None, Region(begin=Location(line=45, column=38), end=Location(line=45, column=40)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00450012_00450024,
    name=FuncDefinitionStatementParserInfoOperatorType.Negative,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=True,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00460012_00460020 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=46, column=12), end=Location(line=46, column=20)), Region(begin=Location(line=46, column=12), end=Location(line=46, column=20))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00460012_00460024 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=46, column=12), end=Location(line=46, column=24)), Region(begin=Location(line=46, column=21), end=Location(line=46, column=24)), Region(begin=Location(line=46, column=12), end=Location(line=46, column=20))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00460012_00460020, ],
)

statement00460005_00480001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=46, column=5), end=Location(line=48, column=1)), Region(begin=Location(line=46, column=5), end=Location(line=46, column=11)), Region(begin=Location(line=46, column=41), end=Location(line=46, column=50)), Region(begin=Location(line=46, column=5), end=Location(line=48, column=1)), Region(begin=Location(line=46, column=25), end=Location(line=46, column=38)), None, None, Region(begin=Location(line=46, column=38), end=Location(line=46, column=40)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00460012_00460024,
    name=FuncDefinitionStatementParserInfoOperatorType.Positive,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=True,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00480012_00480020 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=48, column=12), end=Location(line=48, column=20)), Region(begin=Location(line=48, column=12), end=Location(line=48, column=20))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00480012_00480024 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=48, column=12), end=Location(line=48, column=24)), Region(begin=Location(line=48, column=21), end=Location(line=48, column=24)), Region(begin=Location(line=48, column=12), end=Location(line=48, column=20))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00480012_00480020, ],
)

statement00480037_00480040 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=48, column=37), end=Location(line=48, column=40)), Region(begin=Location(line=48, column=37), end=Location(line=48, column=40))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00480037_00480050 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=48, column=37), end=Location(line=48, column=50)), Region(begin=Location(line=48, column=41), end=Location(line=48, column=50)), Region(begin=Location(line=48, column=37), end=Location(line=48, column=40))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00480037_00480040, ],
)

statement00480037_00480058 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=48, column=37), end=Location(line=48, column=58)), None, None, Region(begin=Location(line=48, column=51), end=Location(line=48, column=58))],  # type: ignore
    is_compile_time=False,
    type=statement00480037_00480050,
    is_variadic=None,
    name="divisor",
    default_value=None,
)

statement00480036_00480059 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=48, column=36), end=Location(line=48, column=59)), None, Region(begin=Location(line=48, column=37), end=Location(line=48, column=58)), None],
    positional=None,
    any_args=[statement00480037_00480058, ],
    keyword=None,
)

statement00480005_00490001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=48, column=5), end=Location(line=49, column=1)), Region(begin=Location(line=48, column=5), end=Location(line=48, column=11)), Region(begin=Location(line=48, column=60), end=Location(line=48, column=69)), Region(begin=Location(line=48, column=5), end=Location(line=49, column=1)), Region(begin=Location(line=48, column=25), end=Location(line=48, column=36)), None, None, Region(begin=Location(line=48, column=36), end=Location(line=48, column=59)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00480012_00480024,
    name=FuncDefinitionStatementParserInfoOperatorType.Divide,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00480036_00480059,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00490012_00490020 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=49, column=12), end=Location(line=49, column=20)), Region(begin=Location(line=49, column=12), end=Location(line=49, column=20))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00490012_00490024 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=49, column=12), end=Location(line=49, column=24)), Region(begin=Location(line=49, column=21), end=Location(line=49, column=24)), Region(begin=Location(line=49, column=12), end=Location(line=49, column=20))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00490012_00490020, ],
)

statement00490039_00490042 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=49, column=39), end=Location(line=49, column=42)), Region(begin=Location(line=49, column=39), end=Location(line=49, column=42))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00490039_00490052 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=49, column=39), end=Location(line=49, column=52)), Region(begin=Location(line=49, column=43), end=Location(line=49, column=52)), Region(begin=Location(line=49, column=39), end=Location(line=49, column=42))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00490039_00490042, ],
)

statement00490039_00490063 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=49, column=39), end=Location(line=49, column=63)), None, None, Region(begin=Location(line=49, column=53), end=Location(line=49, column=63))],  # type: ignore
    is_compile_time=False,
    type=statement00490039_00490052,
    is_variadic=None,
    name="multiplier",
    default_value=None,
)

statement00490038_00490064 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=49, column=38), end=Location(line=49, column=64)), None, Region(begin=Location(line=49, column=39), end=Location(line=49, column=63)), None],
    positional=None,
    any_args=[statement00490039_00490063, ],
    keyword=None,
)

statement00490005_00500001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=49, column=5), end=Location(line=50, column=1)), Region(begin=Location(line=49, column=5), end=Location(line=49, column=11)), Region(begin=Location(line=49, column=65), end=Location(line=49, column=74)), Region(begin=Location(line=49, column=5), end=Location(line=50, column=1)), Region(begin=Location(line=49, column=25), end=Location(line=49, column=38)), None, None, Region(begin=Location(line=49, column=38), end=Location(line=49, column=64)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00490012_00490024,
    name=FuncDefinitionStatementParserInfoOperatorType.Multiply,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00490038_00490064,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00500012_00500020 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=50, column=12), end=Location(line=50, column=20)), Region(begin=Location(line=50, column=12), end=Location(line=50, column=20))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00500012_00500024 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=50, column=12), end=Location(line=50, column=24)), Region(begin=Location(line=50, column=21), end=Location(line=50, column=24)), Region(begin=Location(line=50, column=12), end=Location(line=50, column=20))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00500012_00500020, ],
)

statement00500036_00500039 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=50, column=36), end=Location(line=50, column=39)), Region(begin=Location(line=50, column=36), end=Location(line=50, column=39))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00500036_00500049 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=50, column=36), end=Location(line=50, column=49)), Region(begin=Location(line=50, column=40), end=Location(line=50, column=49)), Region(begin=Location(line=50, column=36), end=Location(line=50, column=39))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00500036_00500039, ],
)

statement00500036_00500058 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=50, column=36), end=Location(line=50, column=58)), None, None, Region(begin=Location(line=50, column=50), end=Location(line=50, column=58))],  # type: ignore
    is_compile_time=False,
    type=statement00500036_00500049,
    is_variadic=None,
    name="exponent",
    default_value=None,
)

statement00500035_00500059 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=50, column=35), end=Location(line=50, column=59)), None, Region(begin=Location(line=50, column=36), end=Location(line=50, column=58)), None],
    positional=None,
    any_args=[statement00500036_00500058, ],
    keyword=None,
)

statement00500005_00520001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=50, column=5), end=Location(line=52, column=1)), Region(begin=Location(line=50, column=5), end=Location(line=50, column=11)), Region(begin=Location(line=50, column=60), end=Location(line=50, column=69)), Region(begin=Location(line=50, column=5), end=Location(line=52, column=1)), Region(begin=Location(line=50, column=25), end=Location(line=50, column=35)), None, None, Region(begin=Location(line=50, column=35), end=Location(line=50, column=59)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00500012_00500024,
    name=FuncDefinitionStatementParserInfoOperatorType.Power,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00500035_00500059,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00520012_00520020 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=52, column=12), end=Location(line=52, column=20)), Region(begin=Location(line=52, column=12), end=Location(line=52, column=20))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00520012_00520024 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=52, column=12), end=Location(line=52, column=24)), Region(begin=Location(line=52, column=21), end=Location(line=52, column=24)), Region(begin=Location(line=52, column=12), end=Location(line=52, column=20))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00520012_00520020, ],
)

statement00520034_00520037 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=52, column=34), end=Location(line=52, column=37)), Region(begin=Location(line=52, column=34), end=Location(line=52, column=37))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00520034_00520047 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=52, column=34), end=Location(line=52, column=47)), Region(begin=Location(line=52, column=38), end=Location(line=52, column=47)), Region(begin=Location(line=52, column=34), end=Location(line=52, column=37))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00520034_00520037, ],
)

statement00520034_00520053 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=52, column=34), end=Location(line=52, column=53)), None, None, Region(begin=Location(line=52, column=48), end=Location(line=52, column=53))],  # type: ignore
    is_compile_time=False,
    type=statement00520034_00520047,
    is_variadic=None,
    name="value",
    default_value=None,
)

statement00520033_00520054 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=52, column=33), end=Location(line=52, column=54)), None, Region(begin=Location(line=52, column=34), end=Location(line=52, column=53)), None],
    positional=None,
    any_args=[statement00520034_00520053, ],
    keyword=None,
)

statement00520005_00530001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=52, column=5), end=Location(line=53, column=1)), Region(begin=Location(line=52, column=5), end=Location(line=52, column=11)), Region(begin=Location(line=52, column=55), end=Location(line=52, column=64)), Region(begin=Location(line=52, column=5), end=Location(line=53, column=1)), Region(begin=Location(line=52, column=25), end=Location(line=52, column=33)), None, None, Region(begin=Location(line=52, column=33), end=Location(line=52, column=54)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00520012_00520024,
    name=FuncDefinitionStatementParserInfoOperatorType.Add,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00520033_00520054,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00530012_00530020 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=53, column=12), end=Location(line=53, column=20)), Region(begin=Location(line=53, column=12), end=Location(line=53, column=20))],
    name="ThisType",
    templates=None,
    constraints=None,
)

statement00530012_00530024 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=53, column=12), end=Location(line=53, column=24)), Region(begin=Location(line=53, column=21), end=Location(line=53, column=24)), Region(begin=Location(line=53, column=12), end=Location(line=53, column=20))],
    mutability_modifier=MutabilityModifier.new,
    items=[statement00530012_00530020, ],
)

statement00530039_00530042 = StandardTypeItemParserInfo.Create(
    regions=[Region(begin=Location(line=53, column=39), end=Location(line=53, column=42)), Region(begin=Location(line=53, column=39), end=Location(line=53, column=42))],
    name="Num",
    templates=None,
    constraints=None,
)

statement00530039_00530052 = StandardTypeParserInfo.Create(
    regions=[Region(begin=Location(line=53, column=39), end=Location(line=53, column=52)), Region(begin=Location(line=53, column=43), end=Location(line=53, column=52)), Region(begin=Location(line=53, column=39), end=Location(line=53, column=42))],
    mutability_modifier=MutabilityModifier.immutable,
    items=[statement00530039_00530042, ],
)

statement00530039_00530058 = FuncParameterParserInfo.Create(
    regions=[Region(begin=Location(line=53, column=39), end=Location(line=53, column=58)), None, None, Region(begin=Location(line=53, column=53), end=Location(line=53, column=58))],  # type: ignore
    is_compile_time=False,
    type=statement00530039_00530052,
    is_variadic=None,
    name="value",
    default_value=None,
)

statement00530038_00530059 = FuncParametersParserInfo.Create(
    regions=[Region(begin=Location(line=53, column=38), end=Location(line=53, column=59)), None, Region(begin=Location(line=53, column=39), end=Location(line=53, column=58)), None],
    positional=None,
    any_args=[statement00530039_00530058, ],
    keyword=None,
)

statement00530005_00540001 = FuncDefinitionStatementParserInfo.Create(
    parser_info_type=ParserInfoType.Standard,
    regions=[Region(begin=Location(line=53, column=5), end=Location(line=54, column=1)), Region(begin=Location(line=53, column=5), end=Location(line=53, column=11)), Region(begin=Location(line=53, column=60), end=Location(line=53, column=69)), Region(begin=Location(line=53, column=5), end=Location(line=54, column=1)), Region(begin=Location(line=53, column=25), end=Location(line=53, column=38)), None, None, Region(begin=Location(line=53, column=38), end=Location(line=53, column=59)), None, None, None, None, None, None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    mutability_param=MutabilityModifier.immutable,
    method_modifier_param=MethodModifier.abstract,
    return_type=statement00530012_00530024,
    name=FuncDefinitionStatementParserInfoOperatorType.Subtract,
    documentation=None,
    templates=None,
    captured_variables=None,
    parameters=statement00530038_00530059,
    statements=None,
    is_deferred=None,
    is_exceptional=None,
    is_generator=None,
    is_reentrant=None,
    is_scoped=None,
    is_static=None,
)

statement00190001_00540001 = ClassStatementParserInfo.Create(
    regions=[Region(begin=Location(line=19, column=1), end=Location(line=54, column=1)), Region(begin=Location(line=19, column=1), end=Location(line=19, column=7)), Region(begin=Location(line=19, column=8), end=Location(line=19, column=17)), Region(begin=Location(line=19, column=26), end=Location(line=19, column=29)), None, None, None, None, Region(begin=Location(line=22, column=2), end=Location(line=54, column=1)), Region(begin=Location(line=19, column=1), end=Location(line=54, column=1)), None, None],
    class_capabilities=ConceptCapabilities,
    visibility_param=VisibilityModifier.public,
    class_modifier_param=ClassModifier.immutable,
    name="Num",
    documentation=None,
    templates=None,
    constraints=statement00190030_00220002,
    extends=None,
    implements=None,
    uses=None,
    statements=[statement00230005_00260005, statement00260005_00270001, statement00270005_00290001, statement00290005_00310001, statement00310005_00330001, statement00330005_00340001, statement00340005_00360001, statement00360005_00380001, statement00380005_00390001, statement00390005_00400001, statement00400005_00410001, statement00410005_00420001, statement00420005_00430001, statement00430005_00450001, statement00450005_00460001, statement00460005_00480001, statement00480005_00490001, statement00490005_00500001, statement00500005_00520001, statement00520005_00530001, statement00530005_00540001, ],
    constructor_visibility_param=VisibilityModifier.public,
    is_abstract=None,
    is_final=None,
)

public_exports = [
    statement00190001_00540001,
]
